# Generated by Django 5.1 on 2024-09-07 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_photocomment_user_photolike'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photocomment',
            options={'ordering': ['-date_time_of_publication']},
        ),
    ]
