# Generated by Django 5.1 on 2024-09-07 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='petphoto',
            options={'ordering': ('-date_of_publication',)},
        ),
    ]
